feat: project structure, docker-compose.yml
mainnpe/java-explore-with-me pull request #2
Opened 2022-11-15 09:42 UTC by mainnpe

Первичный PR для проверки структуры проекта

2022-12-01 17:53 UTC, eugene-lenkevich requested changes
Привет, Артём, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки :)

В первую очередь попробуй настроить форматы дат, это позвоить убрать кучу аннотаций с форматами, это сразу бросается в глаза.
Так же посмотри на то как используется Optional

Лучше не использовать Optional.get() и Optional.empty(), вся фишка в том что мы можем писать код в функциональном стиле, без ветвлений if-else (по крайней мере в явном виде)

https://habr.com/ru/company/otus/blog/668794/

вот примерно так 

![image](https://user-images.githubusercontent.com/94845100/205124804-34770e5e-a0cd-463e-8b76-3fa364634784.png)

А так, работа выполнена шикарно, все эти замечания,  в общем то, просто стилистика :)

Удачи!

2022-12-01 17:53 UTC, eugene-lenkevich commented on ewm-main/src/main/java/ru/practicum/ewmmain/controller/AdminController.java
> +                                        @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2022-12-01 17:53 UTC, eugene-lenkevich commented on ewm-main/src/main/java/ru/practicum/ewmmain/controller/PrivateController.java
> +                                 @PathVariable @NotNull @Min(1) Long userId) {
@Min(1)

А зачем, семантически это ограничение бесполезно, идентификатор пользователя - технические детали, и, в общем случае, он может быть и 0 и -1 :)

Мне кажется достаточно чтобы был @notNull

2022-12-01 17:53 UTC, eugene-lenkevich commented on ewm-main/src/main/java/ru/practicum/ewmmain/dto/event/EventMapper.java
> +            Field fieldToUpdate = ReflectionUtils.findField(Event.class,
Ох ну и завернул рефлексию :)

2022-12-01 17:53 UTC, eugene-lenkevich commented on ewm-main/src/main/java/ru/practicum/ewmmain/service/CategoryServiceImpl.java
> +            log.warn("Category with name '{}' already exists", dto.getName());
Не совсем понял, если имя уже существует то мы только выводим сообщение в лог и все, но даем создать такую сущность, так и задумано? :)

2022-12-01 17:53 UTC, eugene-lenkevich commented on ewm-main/src/main/java/ru/practicum/ewmmain/service/CategoryServiceImpl.java
> +        if (!categoryRepository.existsById(id)) {
Можно сделать это одним запросом, categoryRepository.findById(id) вернет же null (или Optional.empty()) :)

2022-12-01 17:53 UTC, eugene-lenkevich commented on ewm-main/src/main/java/ru/practicum/ewmmain/service/CompilationServiceImpl.java
> +        if (eventOpt.isEmpty()) {
Compilation compilation = compilationRepository.findById(compId).orElseThrow()
или
Compilation compilation = compilationRepository.findById(compId).orElse(null)
в зависимости от того, что требуется
и не надо будет потом делать всякие compilationOpt.get() так как от Optional мы избавимся :)

2022-12-02 15:58 UTC, mainnpe commented on ewm-main/src/main/java/ru/practicum/ewmmain/controller/AdminController.java
> +                                        @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Привет! Спасибо за ревью! Все постарался учесть в этой версии! 
У меня сразу были мысли по поводу глобавльных конфигов, бежал пораньше сдать первую итерацию диплома и предчувствовал, что буду фиксить это в замечаниях :) так и произошло)

2022-12-02 16:10 UTC, mainnpe commented on ewm-main/src/main/java/ru/practicum/ewmmain/service/CategoryServiceImpl.java
> +            log.warn("Category with name '{}' already exists", dto.getName());
Ограничение на уровне базы прописано. То есть категория не создается. Я почему решил так сделать: во первых требования в спецификации к API навели меня на мысли: 
![image](https://user-images.githubusercontent.com/84171339/205334948-6f6dfe76-16e4-4ce9-acdb-566babcde6d1.png)
 
Увидел, что message идет прямиком из БД и решил воспользоваться существующим Spring-овым DataIntegrityViolationException, в которое он мапит ошибки ConstraintVilation из БД, и обрабатывал его, чтобы отдать клиенту конфликт, в случае таких запросов. Знаю, что есть минусы у такого подхода, но так как конкретных требований не было, то выбрал этот вариант, не стал кастомный эксепшн писать для такого случая. 

Понимаю, что проверка на существование и запись только в лог сбивает с толку человека, который в первый раз читает код. Как лучше в таком случае делать?)

2022-12-02 16:11 UTC, mainnpe commented on ewm-main/src/main/java/ru/practicum/ewmmain/service/CategoryServiceImpl.java
> +        if (!categoryRepository.existsById(id)) {
Исправил!

2022-12-02 16:11 UTC, mainnpe commented on ewm-main/src/main/java/ru/practicum/ewmmain/service/CompilationServiceImpl.java
> +        if (eventOpt.isEmpty()) {
Done:))

2022-12-02 16:18 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо, теперь гораздо выразительнее стало :)

2022-12-02 18:34 UTC, eugene-lenkevich commented on ewm-main/src/main/java/ru/practicum/ewmmain/controller/PrivateController.java
> +                                 @PathVariable @NotNull @Min(1) Long userId) {
Ну, на самом деле не думаю что можно однозначно сказать, но если подумать вот с какой точки зрения - допустим злоумышленник перебирает ид пользователей, пытается по ним получить доступ, бедет ид и обращается по нему, получает невнятную ошибку с непонятным сообщением и не знает то ли пользователя нет то ли доступ закрыт. А тут ему будет такая подсказка что идентификаторы пользователей могут быть только вот такие :)
Но, вообще, я б не заморачивался, пользователи не будут вводит эти идентификаторы руками, они вообще их видеть не будут

2022-12-03 04:51 UTC, merged